### ISSUE TITLE
Problem with the cave

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/CaveBlock#41]
In the last few days a big problem has arisen.

As soon as I restart the server, users who have previously created a cave, after rebooting, find themselves without cave. I'll explain:

After restarting the server, if a player enters the server and types / cave it teleports them to the cave but does not make them build or do anything else, as if the cave was no longer his. If I try to type the command / cva info in that place it tells me that I am not in a cave.

So every time I have to reset the player slot and create a new one but restarting the server, after restarting the same problem persists and the player can no longer do anything inside the slot.

it is strange because typing / cave the player is transported to that place but it cannot do anything and if I check with / cva info it tells me that it is not a cave.

How can this be solved? It is causing me a lot of damage.

I use the latest versions of Bentobox and addons (Except for the challenges that I use an older version but that's not the problem). I have also tried with the latest snapshot versions but nothing changes. Using paper 1.15.2 (The latest version # 90)

**Comment by Poslovitch** [comment]
Have you made any changes to island distances and sizes in the config?

**Comment by Manu5656** [comment]
Recently no, I changed the settings at the beginning and I never had any problems. Once they changed automatically by updating the plugin and then I put them back as before.

However I also tried in a new server, so starting from scratch and I had the same problem

**Comment by Manu5656** [comment]
I need a solution as soon as possible, this situation has already been going on for two days and it is creating many problems for me

**Comment by Manu5656** [comment]
@Poslovitch @BONNe @tastybento

**Comment by BONNe** [comment]
Could you provide output of:
/bentobox v
/cba info - for cave that is without an owner
config for caveblock

**Comment by Manu5656** [comment]
> bentobox v
[13:02:12 INFO]: In esecuzione PAPER 1.15.2.
[13:02:12 INFO]: Versione BentoBox: 1.11.1-SNAPSHOT-b1637
[13:02:12 INFO]: Database: JSON
[13:02:12 INFO]: Mondi di gioco caricati:
[13:02:12 INFO]: acidisland_world (AcidIsland): Overworld, [nether_color]Nether, [end_color]End
[13:02:12 INFO]: caveblock-world (CaveBlock): Overworld, [nether_color]Nether, [end_color]End
[13:02:12 INFO]: Componenti aggiuntivi caricati:
[13:02:12 INFO]: AcidIsland 1.11.1-SNAPSHOT-b634 (ENABLED)
[13:02:12 INFO]: Biomes 1.6.0.1-SNAPSHOT-b151 (ENABLED)
[13:02:12 INFO]: CaveBlock 1.10.0-SNAPSHOT-b251 (ENABLED)
[13:02:12 INFO]: Challenges 0.8.0-SNAPSHOT-#323 (ENABLED)
[13:02:12 INFO]: Level 1.9.4-SNAPSHOT-b345 (ENABLED)
[13:02:12 INFO]: VoidPortals 1.5.0.0 (ENABLED)
[13:02:12 INFO]: Warps 1.9.3-SNAPSHOT-b222 (ENABLED)


For your second request I did not understand what I have to show you @BONNe

**Comment by BONNe** [comment]
First of all, you need to use a 1.11 caveblock. That is not a reason why users are losing their caves, but some permissions may not work.

Go to cave what was lost. To a player cave where a player is not an owner after the restart. And write `/cba info`.
Config file can be found in /plugins/bentobox/addons/caveblock folder.

**Comment by Manu5656** [comment]
Yes, before I used that version, I tried the snapshots to see if something changed. Now I put the official versions again.

If the user tries to break blocks, the following is written: Error: Block braking disabled

While doing the command /cba info I see this: You are not in a cave right now ...

As if after the restart the user no longer had his cave, but typing /cave is teleported there

**Comment by Manu5656** [comment]
This is my config
https://hastebin.com/eqoyojubav.coffeescript

**Comment by BONNe** [comment]
So, we need to wait until @Poslovitch or @tastybento replies, but if `/cba info` says that you are not on the cave, it looks like cave grid is broken.
How did you put a player back on the cave?

**Comment by Manu5656** [comment]
Since the cave was not working, I deleted that one and made the player create another one. Creating a new slot works however after restarting the server there is this problem.

I also tried in a new server, with a database and empty world and there was the same problem

**Comment by BONNe** [comment]
can you share data from `/plugins/bentobox/database/islands` folder?

**Comment by Manu5656** [comment]
They are very many files

**Comment by BONNe** [comment]
some files that starts with caveblock

**Comment by Manu5656** [comment]
Those who have created the cave in the past do not have this problem but all the users who create it in the last two days do

**Comment by Manu5656** [comment]
So they are not all "damaged", I can try to find the one of the user with whom I have tried now

**Comment by BONNe** [comment]
hmm...
I would like to see one old, which is working, and a new, that is not.

**Comment by Manu5656** [comment]
I checked through the player's uuid but I can't find it inside the folder and it can actually make sense, since from the game it turns out that this is not a cave so it is as if the file concerning it has also been deleted .. not know

**Comment by Manu5656** [comment]
in /BentoBox/database/Players there is the file of that player instead

**Comment by BONNe** [comment]
Any errors in console?

**Comment by Manu5656** [comment]
When do I start the server or when does the player go to the cave?

**Comment by BONNe** [comment]
So, island UUID is not the same as player UUID. 
Can you share newest stored caveblock and oldest stored caveblock data?
And any error message at all.

**Comment by Manu5656** [comment]
When I start the server I see this:

`[13:13:00 INFO]: [BentoBox] Hooking with Multiverse-Core...
[13:13:00 INFO]: Multiverse already knows about 'acidisland_world'!
[13:13:00 INFO]: Success! Property generator was set to BentoBox
[13:13:00 INFO]: Multiverse already knows about 'acidisland_world_nether'!
[13:13:00 INFO]: Success! Property generator was set to BentoBox
[13:13:00 INFO]: Multiverse already knows about 'acidisland_world_the_end'!
[13:13:00 INFO]: Success! Property generator was set to BentoBox
[13:13:00 INFO]: Multiverse already knows about 'caveblock-world'!
[13:13:00 INFO]: Success! Property generator was set to BentoBox
[13:13:00 INFO]: [BentoBox] Hooking with WorldEdit...
[13:13:00 WARN]: [BentoBox] Loaded class com.sk89q.worldedit.WorldEdit from WorldEdit v1.15-62;8f82a76 wh
ich is not a depend, softdepend or loadbefore of this plugin.
[13:13:00 INFO]:
 ____             _        ____
|  _ \           | |      |  _ \             by tastybento and Poslovitch
| |_) | ___ _ __ | |_ ___ | |_) | _____  __  2017 - 2019
|  _ < / _ \ '_ \| __/ _ \|  _ < / _ \ \/ /
| |_) |  __/ | | | || (_) | |_) | (_) >  <   v1.11.0
|____/ \___|_| |_|\__\___/|____/ \___/_/\_\  Loaded in 1711ms.

[13:13:00 INFO]: [CoreProtect] WorldEdit logging successfully initialized.
[13:13:00 INFO]: [AuctionHouse] Registered Service Provider Vault for Vault's Economy API
[13:13:00 INFO]: [AuctionHouse] Registered Service Provider LuckPerms for Vault's Chat API
[13:13:00 INFO]: [ShopGUIPlus] Using EpicSpawners for spawner support!
[13:13:00 INFO]: [ShopGUIPlus] Loaded 6 main menu items!
[13:13:00 INFO]: [ShopGUIPlus] Loaded 6 shops with total of 132 items!
[13:13:00 INFO]: [Citizens] Could not fetch NMS field bJ: [[bJ.
[13:13:00 INFO]: [Citizens] Could not fetch NMS field bJ: [[null.
[13:13:00 INFO]: [PlaceholderAPI] 166 placeholder expansions are available on the cloud.
[13:13:00 INFO]: [PlaceholderAPI] 1 installed expansions have updates available.
[13:13:00 INFO]: [Citizens] Loaded 250 NPCs.
[13:13:00 INFO]: [LeaderHeadsRevamped] Creating MVdWPlaceholderAPI placeholders
[13:13:00 INFO]: [MVdWPlaceholderAPI] LeaderHeadsRevamped added custom placeholder {leaderheads_*_*_*_*}
[13:13:00 INFO]: [LeaderHeadsRevamped] Creating PlaceholderAPI placeholders
[13:13:00 INFO]: [BentoBox] Added world AcidIsland (NORMAL)
[13:13:01 INFO]: --------------------
[13:13:01 INFO]: [CoreProtect] Version 2.18.0 is now available.
[13:13:01 INFO]: [CoreProtect] Download: www.coreprotect.net/download/
[13:13:01 INFO]: --------------------
[13:13:01 INFO]: [Sponsor] Unlimited Minecraft Hosting: hosthorde.com
[13:13:01 INFO]: --------------------
[13:13:45 INFO]: [BentoBox] Added world CaveBlock (HARD)
[13:13:45 INFO]: [HolographicDisplays] Found a new version available: v2.4.1
[13:13:45 INFO]: [HolographicDisplays] Download it on Bukkit Dev:
[13:13:45 INFO]: [HolographicDisplays] dev.bukkit.org/projects/holographic-displays
[13:13:45 WARN]: Can't keep up! Is the server overloaded? Running 46306ms or 926 ticks behind
[13:13:45 INFO]: [Vault] Checking for Updates ...
[13:13:45 INFO]: [BentoBox] Loaded Blueprint Bundle 'default' for AcidIsland.
[13:13:45 INFO]: [BentoBox] Loaded Blueprint Bundle 'default' for CaveBlock.
[13:13:45 INFO]: [BentoBox] Loaded blueprint 'cave' for CaveBlock
[13:13:45 INFO]: [BentoBox] Loaded blueprint 'cave-copia' for CaveBlock
[13:13:45 WARN]: [BentoBox] Blueprint end-cave.blu had no bedrock block in it so one was added automatica
lly in the center. You should check it.
[13:13:45 INFO]: [BentoBox] Loaded blueprint 'end-cave' for CaveBlock
[13:13:45 INFO]: [BentoBox] Loaded blueprint 'end-island-copia' for AcidIsland
[13:13:45 INFO]: [BentoBox] Loaded blueprint 'end-backup' for AcidIsland
[13:13:45 INFO]: [BentoBox] Loaded blueprint 'end-island' for AcidIsland
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'island' for AcidIsland
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'isola' for AcidIsland
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'nether-backup' for AcidIsland
[13:13:46 INFO]: [Vault] No new version available
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'nether-island-backup' for AcidIsland
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'nether-island-copia' for AcidIsland
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'nether-island' for AcidIsland
[13:13:46 INFO]: [BentoBox] Loaded blueprint 'temple' for AcidIsland`

**Comment by Manu5656** [comment]
Exactly what data would you need?

**Comment by Manu5656** [comment]
I tried on a new server by having new files created and until I entered the config I used before caveblock it worked. So the problem is within the cave-block config. But I didn't change anything in that config .. unless when I updated the plugin to version 1.11 something changed in the file ..

**Comment by Manu5656** [comment]
Ok I understand that the problem is with the start coordinates in the config.

If there are numbers other than 0 set to start-x and start-y this problem occurs. But I have always had other numbers set and since I updated the plugin it gives me this problem ..

**Comment by BONNe** [comment]
Oh, offsets were broken:
https://github.com/BentoBoxWorld/BentoBox/commit/90ad75baa94c7b1dcfc68c1316bb9bd60def82f8
It was fixed, and in the end, broke your world.

**Comment by Manu5656** [comment]
So what should I do? :\

**Comment by Manu5656** [comment]
I also tried with the old versions but the problem remains the same

**Comment by Poslovitch** [comment]
@tastybento You should have a look at this issue. I doubt that reverting the change will be good. There is no point bringing back a bug. However, can we do something to try to prevent such issues in the future? Such as "analyzing" some sensitive settings in the config and actually copy/paste the islands all over the world in order to make them follow the new grid?

**Comment by tastybento** [comment]
There is a bug here. You will need to recover from database backups once it is fixed.
